import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css"; // Ignore the "Can't Find Module" warning - it totally does
import { useMediaQuery } from "usehooks-ts";

import { AuthProvider } from "@/components/context/Auth";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { MenuProvider } from "@/components/context/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <MenuProvider>
            <Header />
            <main className="flex-1 overflow-y-auto">{children}</main>
            <Footer />
          </MenuProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
