# Server
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.datasource.jdbc.max-size=16

# Misc
quarkus.log.console.level=INFO

# CORS
quarkus.http.cors.methods=GET,POST,OPTIONS,PUT,DELETE
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,authorization
quarkus.http.cors.access-control-max-age=24H