# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pizza
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/slice
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Logging
quarkus.log.console.level=DEBUG

# CORS for local frontend
quarkus.http.cors.origins=http://localhost:3000
