# Database TODO point to supabase db
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pizza
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/slice
quarkus.hibernate-orm.database.generation=update

# Logging
quarkus.log.console.level=DEBUG

# CORS for Railway dev frontend
quarkus.http.cors.origins=https://sliceisrightpizzeria.up.railway.app

# JWT
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY}
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY}