# Server
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.datasource.jdbc.max-size=16

# Logs
quarkus.log.level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b "%{i,Referer}" "%{i,User-Agent}"
quarkus.log.category."io.quarkus.resteasy.reactive.server.core".level=DEBUG
quarkus.log.category."org.jboss.resteasy.reactive.common.core".level=DEBUG
quarkus.log.category."io.quarkus.resteasy.reactive.server".level=DEBUG
quarkus.log.category."io.quarkus.resteasy.reactive.server.handlers".level=DEBUG
quarkus.log.category."io.quarkus.resteasy.reactive.server.runtime".level=DEBUG
quarkus.log.category."io.quarkus".level=DEBUG
quarkus.log.category."javax".level=DEBUG
quarkus.log.category."org.hibernate".level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# CORS
# quarkus.http.cors=true
# quarkus.http.cors.origins=http://localhost:3000
# quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
# quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
# quarkus.http.cors.exposed-headers=Content-Disposition
# quarkus.http.cors.access-control-max-age=24H
# quarkus.http.cors.access-control-allow-credentials=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem 
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.native.resources.includes=publicKey.pem,privateKey.pem
mp.jwt.verify.issuer=${JWT_ISSUER:sliceisright}
smallrye.jwt.new-token.key-encryption-algorithm=RSA-OAEP-256
smallrye.jwt.new-token.content-encryption-algorithm=A256CBC-HS512
quarkus.smallrye-jwt.blocking-authentication=true

# Oauth
quarkus.oauth2.client-id=${OAUTH_CLIENT_ID:client}
quarkus.oauth2.client-secret=${OAUTH_CLIENT_SECRET:secret}
quarkus.oauth2.introspection-url=http://oauth-server/introspect
quarkus.oidc.application-type=hybrid