quarkus.log.console.level=DEBUG
quarkus.hibernate-orm.log.sql=true

# Automatically update schema (useful for dev/testing)
quarkus.hibernate-orm.database.generation=drop-and-create

# Serve static files directly from /src/main/resources/META-INF/resources
quarkus.http.host=0.0.0.0


quarkus.http.ssl-port=8443
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=${KEYSTORE_PASSWORD}
quarkus.http.insecure-requests=redirect

quarkus.http.cors=true
quarkus.http.cors.origins=https://localhost:3000