# Database TODO point to supabase db
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pizza
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=jdbc:postgresql://<prod-db-host>:5432/slice
quarkus.hibernate-orm.database.generation=none

# CORS for production frontend
quarkus.http.cors.origins=https://www.sliceisrightpizzeria.com

# Disable detailed errors and enable compression
quarkus.http.show-error-in-response=false
quarkus.http.enable-compression=true
