quarkus.hibernate-orm.database.generation=none
quarkus.http.port=8080

# Disable detailed errors in HTTP responses
quarkus.http.show-error-in-response=false

# Enable compression for faster responses
quarkus.http.enable-compression=true

quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=https://www.sliceisrightpizzeria.com