quarkus.log.console.level=DEBUG
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.http.host=0.0.0.0
quarkus.http.ssl-port=8443
quarkus.http.ssl.certificate.key-store-file=/deployments/keystore.jks
quarkus.http.ssl.certificate.key-store-password=${KEYSTORE_PASSWORD}
quarkus.http.insecure-requests=redirect
quarkus.http.cors=true
quarkus.http.cors.origins=https://localhost:3000