# Use Red Hat Universal Base Image with OpenJDK 21
FROM registry.access.redhat.com/ubi9/openjdk-21:1.23

ENV LANGUAGE='en_US:en'

# Copy Quarkus build artifacts
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

# Copy keystore for HTTPS
COPY ../../../keystore.jks /deployments/keystore.jks

EXPOSE 8080 8443

# Run as non-root user
USER 185

# Declare build argument
ARG KEYSTORE_PASSWORD=password

# Use it in ENV
ENV JAVA_OPTS_APPEND="-Dquarkus.http.ssl.certificate.key-store-password=${KEYSTORE_PASSWORD} \
                     -Dquarkus.http.host=0.0.0.0 \
                     -Dquarkus.http.ssl-port=8443 \
                     -Dquarkus.http.insecure-requests=redirect"

ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
