FROM quay.io/quarkus/ubi-quarkus-native-image:22.3-java17 AS build
WORKDIR /work/
COPY pom.xml .
COPY src ./src
RUN ./mvnw package -DskipTests

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /work/target/*-runner.jar /work/application.jar
EXPOSE 8080
CMD ["java", "-jar", "/work/application.jar"]